### ISSUE TITLE
What's the type of domain and range?

### ISSUE THREAD

**Issue by viweis** [turtlegrammar/faconne#7]
Sorry to bother you again.

When I want to transfer a complex data source, the  domain and range is complex too. I want to save domain and range as string or variable such as:
``` Clojure
(def data {:A 1})

(def source {:A 'a})

(def destination {:A 'a})

(faconne.core/transform data
                      source
                      destination)

```
which fails. I get nil. I also try this

``` Clojure
(faconne.core/transform data
                     (read-string "{:A a}")
                     (read-string "{:A a}")
 )

``` 

Failed again. I get nil. I solve the problem by 

``` Clojure
(eval (concat ['faconne.core/transform  data] [source destination]))
```

But when data is too large or complex, for eval, the form `(concat ['faconne.core/transform  data] [source destination])` is too large. Clojure reports a bug  `Method code too large!`

If I write domain and range directly in faconne form. It's ok no matter how big or complex the data is. Such as: 
``` Clojure
(-> data
      (faconne.core/transform {:A a} {:A a})
)
```
which is correct.

So I'm confused what's the type of domain and range. And what should I do to seperate domain and range from faconne expression?

**Comment by viweis** [comment]
Maybe this is more clear:
``` Clojure
(defn j2j [s d]
  (faconne.core/transform {:a 1} s d)
  )

(j2j {:a a} {:a a})
```
which fails.

Why can not domain and range  be treated as input of a function? In my mind, everything can be variables of function

**Comment by turtlegrammar** [comment]
`transform` and `transformer` are [macros](https://www.braveclojure.com/writing-macros/), which means they extend the syntax of Clojure just like `->`, `if`, `cond`, etc.

Writing this:

```clj
(defn j2j [s d]
  (faconne.core/transform {:a 1} s d) )

(j2j {:a a} {:a a})
```

is equivalent to trying something like:

```clj
(defn arrow-2
  [x y]
  (->> x y))

(arrow-2 [1 2] (mapv inc))

; ArityException Wrong number of args (1) passed to: core/mapv  clojure.lang.AFn.throwArity (AFn.java:429)

```

Here's an example of macro-expanding a `transform`:
 
```clj
(macroexpand-1 '(faconne.core/transform {1 [2 3], 3 [2 4], 4 [5]} {k [v]} {v #{k}}))
;; =>
(clojure.core/let
 [f__11518__auto__ (faconne.core/transformer {k [v]} {v #{k}})]
 (f__11518__auto__ {1 [2 3], 3 [2 4], 4 [5]}))

(macroexpand-1 '(faconne.core/transformer {k [v]} {v #{k}}))
;; =>
(clojure.core/fn
 [structure8005]
 (clojure.core/let
  [result8004 (clojure.core/volatile! {})]
  (clojure.core/doseq
   [[k map-val-parent8006] structure8005]
   (clojure.core/doseq
    [vec-parent8007 map-val-parent8006]
    (clojure.core/let [v vec-parent8007] (clojure.core/vswap! result8004 faconne.compile/deep-merge {v #{k}}))))
  @result8004))
```

`transform` is a macro for a good reason: as you can see, creating a function from the domain and range takes a lot of logic. If `transform` weren't a macro, we would have to do this at runtime, which would slow down every call to `transform`. I wanted faconne to be just as fast as writing transformations manually. Because `transform` is a macro, we can build this function at compile time, and not suffer any loss in speed compared to writing the `transform` manually.

You _can_ get around this, but you will suffer a performance hit. I don't know how severe it is; it may not make much of a difference. You could do this:

```clj
(defn transform-as-a-function
  [data domain range]
  (eval `(faconne.core/transform ~data ~domain ~range)))

(def domain '{k [v]})
(def range '{v #{k}})

(transform-as-a-function {1 [2 3], 3 [2 4], 4 [5]} domain range)
;; =>
{2 #{1 3}, 3 #{1}, 4 #{3}, 5 #{4}}
```

Notice the `'` character in `(def domain '{k [v]})` and `(def range '{v #{k}})` -- this means you are quoting code, and passing unevaluated code to the function. The `'` operator (called 'quote') is explained in the macro link above. 

You can see the types of every subexpresson of `'{k [v]}` here:

```clj
(defn recursive-types
  [x]
  (cond (symbol? x) {x (type x)}
    (vector? x) (apply merge {x (type x)} (mapv recursive-types x))    
    (map? x) (merge (clojure.walk/walk recursive-types merge x) {x (type x)})))

(recursive-types '{k [v]})
; =>
{[k [v]] clojure.lang.MapEntry,
 k clojure.lang.Symbol,
 [v] clojure.lang.PersistentVector,
 v clojure.lang.Symbol,
 {k [v]} clojure.lang.PersistentArrayMap}
```

**Comment by viweis** [comment]
Thanks for your answer. 

But when the data you want to transform is too large or complex, for Clojure method eval, the form XXX in `(eval XXX) ` is too large. Clojure reports a bug Method code too large! Because Clojure has a limit , the form need to be within 64k. Java also has the limit.

But if I use faconne directly, it works well. Seems no matter how big the data is, faconne can work well. 

So I give up the method eval. And I was told it’s better to use function rather than macro and it’s better to use macro rather than eval.

**Comment by turtlegrammar** [comment]
I think you can use the following to avoid the exception you're describing:

```clj
(defn transform-as-a-function-2
  [data domain range]
  (let [f (eval `(faconne.core/transformer ~domain ~range))]
    (f data)))

(transform-as-a-function-2 {1 [2 3] 4 [5 2]} '{k [v]} '{v [k]})
;; =>
{2 [1 4], 3 [1], 5 [4]}
```

This avoids passing the data you're transforming to `eval`.
